services:
  cms:
    image: crpi-i9di0h4v1o29h468.cn-shenzhen.personal.cr.aliyuncs.com/lanx_x/longwang-cms:${IMAGE_TAG:-latest}
    pull_policy: always
    container_name: lw-cms
    restart: unless-stopped
    ports:
      - "11337:1337"
    volumes:
      - ./apps/cms/data:/app/apps/cms/data
      - ./apps/cms/public/uploads:/app/apps/cms/public/uploads
    env_file:
      - ./apps/cms/.env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0

  web:
    image: crpi-i9di0h4v1o29h468.cn-shenzhen.personal.cr.aliyuncs.com/lanx_x/longwang-web:${IMAGE_TAG:-latest}
    pull_policy: always
    container_name: lw-web
    restart: unless-stopped
    ports:
      - "33000:3000"
    depends_on:
      - cms
    env_file:
      - ./apps/web/.env
    environment:
      NODE_ENV: production
