import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { defaultLocale, isLocale, type Locale } from "@/i18n";
import { Broadcast } from "@/components/Broadcast";
import { Nav } from "@/components/Nav";
import { getNavigation, getSite, getBroadcast, getI18nLocales } from "@/api";
import { Footer } from "@/components/Footer";
import { FloatingActions } from "@/components/FloatingActions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale: routeLocale } = await params;
  const locale: Locale = isLocale(routeLocale) ? routeLocale : defaultLocale;

  const { data: navData } = await getNavigation("owqgz3ze0n1a15777qpdokl0", { locale });
  const site = await getSite()
  const broadcasts = await getBroadcast({ locale })
  const localeList = await getI18nLocales()

  return (
    <html lang={locale} className={`h-full antialiased`}>
      <body className={`${roboto.variable} min-h-full flex flex-col font-sans`}>
        <Broadcast currentLocale={locale} data={broadcasts.data} site={site.data} localeList={localeList} />
        <Nav data={navData} site={site.data} locale={locale} />
        {children}
        <Footer navigation={navData} locale={locale} site={site.data} />
        <FloatingActions site={site.data} />
      </body>
    </html>
  );
}
