// This file is auto-generated by scripts/generate-assets.mjs.
// Do not edit it by hand.

import AllCat from "./all-cat.svg";
import ArrowR from "./arrow-r.svg";
import Avatar from "./avatar.png";
import Banner from "./banner.png";
import BlackArrowL from "./black-arrow-l.svg";
import BlackArrowR from "./black-arrow-r.svg";
import Broadcast from "./broadcast.svg";
import Building from "./building.jpg";
import Cap from "./cap.jpg";
import CaretSmallLeft from "./caret-small-left.svg";
import CaretSmallRight from "./caret-small-right.svg";
import CheckBlue from "./check-blue.png";
import Check from "./check.svg";
import Close from "./close.svg";
import ComCat from "./com-cat.svg";
import Contact from "./contact.png";
import Corp01 from "./corp-01.svg";
import Corp02 from "./corp-02.svg";
import Corp03 from "./corp-03.svg";
import Corp04 from "./corp-04.svg";
import Corp05 from "./corp-05.png";
import EmailBlue from "./email-blue.svg";
import EquipBase from "./equip-base.png";
import EquipListBg from "./equip-list-bg.svg";
import Expand from "./expand.svg";
import Facebook from "./facebook.svg";
import GrayArrowL from "./gray-arrow-l.svg";
import GrayArrowR from "./gray-arrow-r.svg";
import In from "./in.svg";
import IndustryCat from "./industry-cat.svg";
import Ins from "./ins.svg";
import Iqc from "./iqc.png";
import Iso from "./iso.png";
import Lang from "./lang.svg";
import LinkCircle from "./link-circle.svg";
import LinkWhite from "./link-white.svg";
import Link from "./link.svg";
import LogoText from "./logo-text.svg";
import Logo from "./logo.svg";
import Mail from "./mail.svg";
import Map from "./map.png";
import Menu from "./menu.svg";
import Milestone from "./milestone.svg";
import Minus from "./minus.svg";
import NavFeaturedArrow from "./nav-featured-arrow.svg";
import Plus from "./plus.svg";
import Ptech from "./ptech.png";
import QuoteL from "./quote-l.svg";
import QuoteR from "./quote-r.svg";
import Ruler1Off from "./ruler-1-off.svg";
import Ruler1On from "./ruler-1-on.svg";
import RulerOff from "./ruler-off.svg";
import RulerOn from "./ruler-on.svg";
import Top from "./top.svg";
import Upload from "./upload.png";
import Whatsapp from "./whatsapp.svg";
import X from "./x.svg";

export const Assets = {
  AllCat,
  ArrowR,
  Avatar,
  Banner,
  BlackArrowL,
  BlackArrowR,
  Broadcast,
  Building,
  Cap,
  CaretSmallLeft,
  CaretSmallRight,
  CheckBlue,
  Check,
  Close,
  ComCat,
  Contact,
  Corp01,
  Corp02,
  Corp03,
  Corp04,
  Corp05,
  EmailBlue,
  EquipBase,
  EquipListBg,
  Expand,
  Facebook,
  GrayArrowL,
  GrayArrowR,
  In,
  IndustryCat,
  Ins,
  Iqc,
  Iso,
  Lang,
  LinkCircle,
  LinkWhite,
  Link,
  LogoText,
  Logo,
  Mail,
  Map,
  Menu,
  Milestone,
  Minus,
  NavFeaturedArrow,
  Plus,
  Ptech,
  QuoteL,
  QuoteR,
  Ruler1Off,
  Ruler1On,
  RulerOff,
  RulerOn,
  Top,
  Upload,
  Whatsapp,
  X,
} as const;
