// This file is auto-generated by scripts/generate-assets.mjs.
// Do not edit it by hand.

import BlackArrowL from "./black-arrow-l.svg";
import BlackArrowR from "./black-arrow-r.svg";
import Close from "./close.svg";
import Dot from "./dot.png";
import IconArrow2 from "./icon_arrow_2.png";
import IconArrow from "./icon_arrow.png";
import IconPlay from "./icon_play.png";
import Map from "./map.png";
import Menu from "./menu.svg";
import Minus from "./minus.svg";
import Plus from "./plus.svg";

export const Assets = {
  BlackArrowL,
  BlackArrowR,
  Close,
  Dot,
  IconArrow2,
  IconArrow,
  IconPlay,
  Map,
  Menu,
  Minus,
  Plus,
} as const;
