import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Assets } from "@/assets";
import { defaultLocale, getDictionary, isLocale, type Locale, I18nProvider } from "@/i18n";
import { Broadcast } from "@/components/Broadcast";
import { Nav } from "@/components/Nav";
import { Subscribe } from "@/components/Subscribe";
import { GetInTouch } from "@/components/GetInTouch";
import { getNavigation, getSite, getBroadcast } from "@/api";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const locale: Locale = isLocale(lang) ? lang : defaultLocale;
  const messages = await getDictionary(locale);

  const { data: navData } = await getNavigation("owqgz3ze0n1a15777qpdokl0", { locale });
  const site = await getSite()
  const broadcasts = await getBroadcast({ locale })

  return (
    <html lang={locale} className={`h-full antialiased`}>
      <body className={`${roboto.variable} min-h-full flex flex-col font-sans`}>
        <I18nProvider locale={locale} messages={messages}>
          <Broadcast data={broadcasts.data} site={site.data} />
          <Nav data={navData} site={site.data} lang={locale} />
          {children}
          <Footer navigation={navData} lang={lang} site={site.data} />
        </I18nProvider>
      </body>
    </html>
  );
}
