import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Assets } from "@/assets";
import { defaultLocale, getDictionary, isLocale, type Locale, I18nProvider } from "@/i18n";
import { Broadcast } from "@/components/Broadcast";
import { Menu } from "@/components/Menu";
import { Subscribe } from "@/components/Subscribe";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});

function Nav() {
  return (
    <div className="">
      <div className="flex flex-row items-center px-5 py-3 xl:w-320 xl:mx-auto" data-nav-root>
        <Image className="w-9 h-9 mr-2" src={Assets.Logo} width={36} height={36} alt="logo" />
        <Image className="w-24 h-3" src={Assets.LogoText} width={96} height={14} alt="logo" />
        <div className="ml-auto">
          <Menu />
        </div>
      </div>
    </div>
  )
}

function Contact() {
  return (
    <div className="relative w-full">
      <Image src={Assets.Contact} alt="contact" fill className="object-cover object-[20%_center] xl:object-[center_center]" />
      <div className="relative text-white px-5 pt-15 pb-16.25 text-center xl:w-7xl xl:mx-auto">
        <h2 className="section-title">Elit autem assumenda enim reprehenderit?</h2>
        <p className="section-desc">Elit libero numquam fugit vitae dignissimos quidem. Numquam ut earum quibusdam incidunt beatae Natus sapiente exercitationem corporis recusandae perferendis. Laudantium!</p>

        <Subscribe className="mt-15.75 xl:mt-15 xl:w-145 xl:mx-auto" />
      </div>
    </div>
  )
}

function Footer() {
  return (
    <div className="px-5 mt-15 xl:px-0 xl:w-7xl xl:mx-auto">
      <div className="flex flex-col xl:flex-row">
        <div className="mb-15 xl:mr-39.5 xl:mb-23">
          <div className="flex flex-row items-center mb-4">
            <Image className="w-10 h-10 mr-3" src={Assets.Logo} alt="logo" />
            <Image className="w-30 h-4" src={Assets.LogoText} alt="logo-text" />
          </div>

          <p className="mb-5 text-base">Elit amet incidunt nesciunt quod a? Perspiciatis dicta quam nostrum.</p>

          <div className="text-sm text-secondary" >
            <p>Tel: 832412414141</p>
            <p>Mobile: 832412414141</p>
            <p>Email: 832412414141@qq.com</p>
            <p className="mt-5">Address: DBuilding,Xianxi Industrial Gardan,Shatou,Zhen an Road,Chang an,Dongguan,China</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-10 mb-10 xl:grid-cols-4">
          {
            [1, 2, 3, 4].map((xs, idx) => (
              <div key={idx}>
                <p className="font-medium text-base mb-6">Dolor</p>
                <ul className="text-sm">
                  <li className="mb-3">Adipisicing adipisicing</li>
                  <li className="mb-3">Amet veritatis</li>
                  <li className="mb-3">Adipisicing vel</li>
                  <li className="mb-3">Adipisicing tenetur?</li>
                </ul>
              </div>
            ))
          }
        </div>
      </div>

      <div className="flex flex-col xl:flex-row-reverse xl:items-center mb-5">
        <Subscribe className="border border-[#efefef] mb-10 xl:w-143 xl:mb-0" />

        <div className="flex flex-row items-center xl:flex-1">
          <Image className="w-6 h-6 mr-6" src={Assets.X} alt="x" />
          <Image className="w-6 h-6 mr-6" src={Assets.Ins} alt="x" />
          <Image className="w-6 h-6 mr-6" src={Assets.Facebook} alt="x" />
          <Image className="w-6 h-6 mr-6" src={Assets.In} alt="x" />
        </div>
      </div>


      <div className="w-full h-px bg-[#efefef]"></div>
      <p className="text-sm text-secondary my-7.5">Copyright © 2018-2025 SlowMist Limited. All Rights Reserved. 闽ICP备18006755号-1  闽公网安备35020302032841号</p>

    </div>
  )
}


export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const locale: Locale = isLocale(lang) ? lang : defaultLocale;
  const messages = await getDictionary(locale);

  return (
    <html
      lang={locale}
      className={`h-full antialiased`}
    >
      <body className={`${roboto.variable} min-h-full flex flex-col font-sans`}>
        <I18nProvider locale={locale} messages={messages}>
          <Broadcast />
          <Nav />
          {children}
          <Contact />
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
