import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const assetsDir = path.join(projectRoot, "src", "assets");
const outputFile = path.join(assetsDir, "index.ts");
const watchMode = process.argv.includes("--watch");
const assetExtensions = new Set([
  ".avif",
  ".gif",
  ".jpeg",
  ".jpg",
  ".png",
  ".svg",
  ".webp",
]);

function toPosixPath(filePath) {
  return filePath.split(path.sep).join("/");
}

function toPascalCase(value) {
  const normalized = value
    .replace(/@(\d+)x/gi, " $1x")
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim();

  const parts = normalized.split(/\s+/).filter(Boolean);
  const identifier = parts
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

  return identifier || "Asset";
}

async function collectAssetFiles(directory) {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolutePath = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await collectAssetFiles(absolutePath)));
      continue;
    }

    const extension = path.extname(entry.name).toLowerCase();
    const isIndexFile = /^index\.[cm]?[jt]sx?$/.test(entry.name);

    if (!assetExtensions.has(extension) || isIndexFile) {
      continue;
    }

    files.push(absolutePath);
  }

  return files.sort((a, b) => a.localeCompare(b));
}

function buildEntries(files) {
  const usedNames = new Map();

  return files.map((filePath) => {
    const relativePath = path.relative(assetsDir, filePath);
    const withoutExtension = relativePath.replace(/\.[^.]+$/, "");
    const pathParts = withoutExtension.split(path.sep).map(toPascalCase);
    let exportName = pathParts.join("");

    if (!exportName) {
      exportName = "Asset";
    }

    const nextCount = (usedNames.get(exportName) ?? 0) + 1;
    usedNames.set(exportName, nextCount);

    if (nextCount > 1) {
      exportName = `${exportName}${nextCount}`;
    }

    return {
      exportName,
      importPath: `./${toPosixPath(relativePath)}`,
    };
  });
}

function buildOutput(entries) {
  const importLines = entries.map(
    ({ exportName, importPath }) => `import ${exportName} from "${importPath}";`,
  );
  const objectLines = entries.map(({ exportName }) => `  ${exportName},`);

  return `${[
    "// This file is auto-generated by scripts/generate-assets.mjs.",
    "// Do not edit it by hand.",
    "",
    ...importLines,
    "",
    "export const Assets = {",
    ...objectLines,
    "} as const;",
    "",
  ].join("\n")}`;
}

async function writeAssetsIndex() {
  const files = await collectAssetFiles(assetsDir);
  const entries = buildEntries(files);
  const output = buildOutput(entries);
  const previous = await fs.readFile(outputFile, "utf8").catch(() => "");

  if (previous === output) {
    return false;
  }

  await fs.writeFile(outputFile, output, "utf8");
  return true;
}

async function generateAndReport() {
  const changed = await writeAssetsIndex();
  const label = changed ? "updated" : "unchanged";
  console.log(`[assets] ${label} ${path.relative(projectRoot, outputFile)}`);
}

async function main() {
  await generateAndReport();

  if (!watchMode) {
    return;
  }

  console.log(`[assets] watching ${path.relative(projectRoot, assetsDir)}`);

  let timer = null;
  const schedule = () => {
    if (timer !== null) {
      clearTimeout(timer);
    }

    timer = setTimeout(async () => {
      timer = null;

      try {
        await generateAndReport();
      } catch (error) {
        console.error("[assets] generation failed");
        console.error(error);
      }
    }, 75);
  };

  const watcher = fs.watch(assetsDir, { recursive: true }, schedule);

  process.on("SIGINT", () => {
    watcher.close();
    process.exit(0);
  });

  process.on("SIGTERM", () => {
    watcher.close();
    process.exit(0);
  });
}

main().catch((error) => {
  console.error("[assets] generation failed");
  console.error(error);
  process.exit(1);
});
