// This file is auto-generated by scripts/generate-assets.mjs.
// Do not edit it by hand.

import Avatar from "./avatar.png";
import Banner from "./banner.png";
import BlackArrowL from "./black-arrow-l.svg";
import BlackArrowR from "./black-arrow-r.svg";
import Broadcast from "./broadcast.svg";
import Building from "./building.jpg";
import Cap from "./cap.jpg";
import Check from "./check.svg";
import Close from "./close.svg";
import Contact from "./contact.jpg";
import Corp01 from "./corp-01.svg";
import Corp02 from "./corp-02.svg";
import Corp03 from "./corp-03.svg";
import Corp04 from "./corp-04.svg";
import Corp05 from "./corp-05.png";
import Expand from "./expand.svg";
import Facebook from "./facebook.svg";
import GrayArrowL from "./gray-arrow-l.svg";
import GrayArrowR from "./gray-arrow-r.svg";
import In from "./in.svg";
import Ins from "./ins.svg";
import Iso from "./iso.png";
import Lang from "./lang.svg";
import Link from "./link.svg";
import LogoText from "./logo-text.svg";
import Logo from "./logo.svg";
import Mail from "./mail.svg";
import Map from "./map.png";
import Menu from "./menu.svg";
import Plus from "./plus.svg";
import QuoteL from "./quote-l.svg";
import QuoteR from "./quote-r.svg";
import RulerOff from "./ruler-off.svg";
import RulerOn from "./ruler-on.svg";
import Top from "./top.svg";
import Whatsapp from "./whatsapp.svg";
import X from "./x.svg";

export const Assets = {
  Avatar,
  Banner,
  BlackArrowL,
  BlackArrowR,
  Broadcast,
  Building,
  Cap,
  Check,
  Close,
  Contact,
  Corp01,
  Corp02,
  Corp03,
  Corp04,
  Corp05,
  Expand,
  Facebook,
  GrayArrowL,
  GrayArrowR,
  In,
  Ins,
  Iso,
  Lang,
  Link,
  LogoText,
  Logo,
  Mail,
  Map,
  Menu,
  Plus,
  QuoteL,
  QuoteR,
  RulerOff,
  RulerOn,
  Top,
  Whatsapp,
  X,
} as const;
