// This file is auto-generated by scripts/generate-assets.mjs.
// Do not edit it by hand.

import Banner from "./banner.png";
import Broadcast from "./broadcast.svg";
import Cap from "./cap.jpg";
import Contact from "./contact.jpg";
import Facebook from "./facebook.svg";
import In from "./in.svg";
import Ins from "./ins.svg";
import Iso from "./iso.png";
import Lang from "./lang.svg";
import LogoText from "./logo-text.svg";
import Logo from "./logo.svg";
import Mail from "./mail.svg";
import X from "./x.svg";

export const Assets = {
  Banner,
  Broadcast,
  Cap,
  Contact,
  Facebook,
  In,
  Ins,
  Iso,
  Lang,
  LogoText,
  Logo,
  Mail,
  X,
} as const;
